version: '3'
services:
  devetek-profile:
    build:
      context: ./
      dockerfile: ./docker/Development
    volumes:
      - ./:/www/app/profile/
    ports:
      - '6500:6500'
      - '6501:6501'
    environment:
      NODE_ENV: development
      DEVETEK_REDIS: devetek.redis.local
    command: ['yarn', 'start']
    container_name: devetek.profile.local
